POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InB1cnBoaWxsIiwiaWQiOiI2MTM4N2M1ODI2ODFmNTBkMzQ2NjEzZTAiLCJpYXQiOjE2MzEzNTE3MTB9.hvCyj1XT8DW7lfMrhX3ikNUGdoDWeZ1ETlGl6WsKpis

{
    "title": "Computer Networking Introduction - Ethernet and IP (Heavily Illustrated)",
    "author": "Ivan",
    "url": "https://iximiuz.com/en/posts/computer-networking-101/?utm_medium=reddit&utm_source=r_programming",
    "likes": 10
}

###

GET http://localhost:3003/api/blogs/ HTTP/1.1

###

POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "adam09",
    "name": "Adam",
    "password": "wario"
}

###

GET http://localhost:3003/api/users/ HTTP/1.1

###

POST http://localhost:3003/api/login/ HTTP/1.1
content-type: application/json

{
    "username": "purphill",
    "password": "yoshi"
}

###

DELETE http://localhost:3003/api/blogs/613c73e3a2594806b4c14309 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InB1cnBoaWxsIiwiaWQiOiI2MTM4N2M1ODI2ODFmNTBkMzQ2NjEzZTAiLCJpYXQiOjE2MzEzNTI4NTF9.bP2iBLk04-c9IX9asNgkuH1_aW3jthZNDezPr_boN24
